In [2]:
import numpy as np

In [2]:
#matrix = ([[1,0.2,0.5],[0.2,1,0.8],[0.5,0.8,1]])
#creating a matrix in array form
matrix = np.array([[1,0.2,0.5],[0.2,1,0.8],[0.5,0.8,1]])
print(matrix)

[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


In [6]:
#calculating matrix inversion of the matrix transpose
#defining the matrix
matrix = np.array([[1,0.2,0.5],[0.2,1,0.8],[0.5,0.8,1]])
#calculating the inverse
inverse_matrix = np.linalg.inv(matrix)
print (inverse_matrix)

[[ 1.56521739  0.86956522 -1.47826087]
 [ 0.86956522  3.26086957 -3.04347826]
 [-1.47826087 -3.04347826  4.17391304]]


In [7]:
#calculating the determinant of matrix
#define the matrix
matrix = np.array([[1,0.2,0.5],[0.2,1,0.8],[0.5,0.8,1]])

#calculating the determinant
determinant = np.linalg.det(matrix)
print(determinant)



0.2299999999999999


In [3]:
#matrix transpose
matrix = np.array([[1,0.2,0.5],[0.2,1,0.8],[0.5,0.8,1]])
matrix_transpose = np.transpose(matrix)
print(matrix_transpose)

[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]
